# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:WAmMieYapKV6BDV4WaPqH0meRdGxQfY8/pYWF9D0zJdlzrXJHZ/+Og==,iv:W6EuMu2HWP4CEQcTfVAJDn5nMCCxFH/rHWbqfdW0yIo=,tag:sdDDlxLIWNR6vUPJEy+dRg==,type:str]
sops:
  age:
    - recipient: age19frvg5nk5crkrxz20qaxmef7tx7uyz83h2fht0d9njc3yec4j5xqk2u37s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTktxOEF0N1Rhc2xjRXpt
        TXlmd3FxM3RYc2VOY2tKTjZXT1pyYkN2V2ljCnpHNmlTb0VhY2JBcEJ3REliTm1S
        RnN1dWxZWjdwRFZVZVZUaW92NnhPQm8KLS0tIEordm1LaVByVGFVNHdnSDBhazB1
        cG8xN3VTeCtVNVZWMG04Sm5pT0lINkEKdx4vFiqeSACgJUkE15T4CmlyrYrnxeYy
        ra7t7p2fJ/81shqQcbFTqd+wuoiqAdUvGwc3oMKMl4Q6X2p5uicu4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-17T02:26:26Z"
  mac: ENC[AES256_GCM,data:SbcGpn1tKQdl6eiJksrgqultrVXsEKv+3HpY50kEIkDIi3noZgIoj5jy+bTqbPw1n2mTvsNbtsffg4bHPuBm69BIpDbqxwSCaadfEuejd6IHrLlLhiZT4TKPqFbrnW7AqBF3NIwECoRCwNJ4ksW8G9KZ/W4g1HuB0yZ0b90UEUs=,iv:7UpVq1DxFb5oyVHfP9VAzQO/3HgwKbW2YiGv5LP3tLY=,tag:iGopgbnus7T9U3kQVPExDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
